export interface GraphData {
    ID: string;
    ISO2: string;
    COUNTRY: string;
    COUNTRY_NUMBER: number;
    SPECIES: string;
    PYRETHROIDS_AVERAGE_MORTALITY: number | "-";
    ORGANOCHLORINES_AVERAGE_MORTALITY: number | "-";
    CARBAMATES_AVERAGE_MORTALITY: number | "-";
    ORGANOPHOSPHATES_AVERAGE_MORTALITY: number | "-";
    MONOXYGENASES_PERCENT_SITES_DETECTED: number | "-";
    MONOXYGENASES_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
    ESTERASES_PERCENT_SITES_DETECTED: number | "-";
    ESTERASES_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
    GSTS_PERCENT_SITES_DETECTED: number | "-";
    GSTS_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
    K1014S_PERCENT_SITES_DETECTED: number | "-";
    K1014S_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
    K1014F_PERCENT_SITES_DETECTED: number | "-";
    K1014F_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
    KDR_UNSPECIFIED_PERCENT_SITES_DETECTED: number | "-";
    KDR_UNSPECIFIED_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
    ACE1R_PERCENT_SITES_DETECTED: number | "-";
    ACE1R_PERCENT_SITES_DETECTED_NUMBER_SITES: number;
}
