export enum LEVEL_OF_INVOLVEMENT {
    FULL_INVOLVEMENT = "FULL_INVOLVEMENT",
    PARTIAL_INVOLVEMENT = "PARTIAL_INVOLVEMENT",
    NO_INVOLVEMENT = "NO_INVOLVEMENT",
    COULD_NOT_BE_RELIABLY_ASSESSED = "COULD_NOT_BE_RELIABLY_ASSESSED",
}
