export enum ActionTypeEnum {
    MalariaSetAny = "malaria/SET_ANY",
    MalariaSetTheme = "malaria/SET_THEME",
    MalariaLogEvent = "malaria/LOG_EVENT",
    MalariaLogPageView = "malaria/LOG_PAGE_VIEW",
    MalariaLogOutboundLink = "malaria/LOG_OUTBOUND_LINK",
    MalariaSetRegion = "malaria/SET_REGION",
    MalariaSetFilters = "malaria/SET_FILTERS",
    MalariaSetMaxMinYears = "malaria/SET_MAX_MIN_YEARS",
    MalariaToogleEndemicityLayer = "malaria/TOGGLE_ENDEMICITY_LAYER",
    MalariaSetStoryMode = "malaria/SET_STORY_MODE",
    MalariaSetStoryModeStep = "malaria/SET_STORY_MODE_STEP",
    MalariaActionGroupSelected = "malaria/ACTION_GROUP_SELECTED",
    SetSelection = "malaria/SET_SELECTION",
    SetHoverSelection = "malaria/SET_HOVER_SELECTION",
    SetSelectionData = "malaria/SET_SELECTION_DATA",
    SetSelectionDataFilterSelection = "malaria/SET_SELECTION_DATA_FILTER_SELECTION",
    SetMobileOptionsOpen = "malaria/SET_MOBILE_OPTIONS_OPEN",
    UpdateZoom = "malaria/UPDATE_ZOOM",
    SetZoom = "malaria/SET_ZOOM",
    UpdateBounds = "malaria/UPDATE_BOUNDS",
    SetBounds = "malaria/SET_BOUNDS",
    SetTourOpen = "malaria/SET_TOUR_OPEN",
    SetTourStep = "malaria/SET_TOUR_STEP",
    SetReportOpen = "malaria/SET_REPORT_OPEN",
    SetMapTitle = "malaria/SET_MAP_TITLE",
    SetUploadFileOpen = "malaria/SET_UPLOAD_FILE_OPEN",
    SetFeedbackOpen = "malaria/SET_FEEDBACK_OPEN",
    SetTheaterMode = "malaria/SET_THEATER_MODE_OPEN",
    SetLegendExpanded = "malaria/SET_LEGEND_EXPANDED",
    GetLastUpdatedRequest = "malaria/GET_LAST_UPDATED_REQUEST",
    GetLastUpdatedSuccess = "malaria/GET_LAST_UPDATED_SUCCESS",
    GetLastUpdatedFailure = "malaria/GET_LAST_UPDATED_FAILURE",

    FetchPreventionStudiesRequest = "prevention/FETCH_PREVENTION_STUDIES_REQUEST",
    FetchPreventionStudiesSuccess = "prevention/FETCH_PREVENTION_STUDIES_SUCCESS",
    FetchPreventionStudiesError = "prevention/FETCH_PREVENTION_STUDIES_ERROR",

    SetPreventionMapType = "prevention/SET_PREVENTION_MAP_TYPE",
    SetPreventionDataset = "prevention/SET_PREVENTION_DATASET",
    SetInsecticideClass = "prevention/SET_INSECTICIDE_CLASS",
    SetInsecticideTypes = "prevention/SET_INSECTICIDE_TYPES",
    SetProxyType = "prevention/SET_PROXY_TYPE",
    SetType = "prevention/SET_TYPE",
    SetSynergistTypes = "prevention/SET_SYNERGIST_TYPES",
    SetSpecies = "prevention/SET_SPECIES",
    SetAssayTypes = "prevention/SET_ASSAY_TYPES",
    SetPreventionFilteredStudies = "prevention/SET_FILTER_STUDIES",
    SetPreventionSelectionStudies = "prevention/SET_SELECTION_STUDIES",

    SetDiagnosisMapType = "diagnosis/SET_DIAGNOSIS_MAP_TYPE",
    SetDiagnosisDataset = "diagnosis/SET_DIAGNOSIS_DATASET",

    FetchDiagnosisStudiesRequest = "diagnosis/FETCH_DIAGNOSIS_STUDIES_REQUEST",
    FetchDiagnosisStudiesSuccess = "diagnosis/FETCH_DIAGNOSIS_STUDIES_SUCCESS",
    FetchDiagnosisStudiesError = "diagnosis/FETCH_DIAGNOSIS_STUDIES_ERROR",

    SetSurveyTypes = "diagnosis/SET_DIAGNOSIS_SURVEY_TYPES",
    SetPatientType = "diagnosis/SET_DIAGNOSIS_PATIENT_TYPE",
    SetDeletionType = "diagnosis/SET_DIAGNOSIS_DELETION_TYPE",
    SetDiagnosisFilteredStudies = "diagnosis/SET_FILTER_STUDIES",
    SetDiagnosisSelectionStudies = "diagnosis/SET_SELECTION_STUDIES",

    FetchTreatmentStudiesRequest = "treatment/FETCH_TREATMENT_STUDIES_REQUEST",
    FetchTreatmentStudiesSuccess = "treatment/FETCH_TREATMENT_STUDIES_SUCCESS",
    FetchTreatmentStudiesError = "treatment/FETCH_TREATMENT_STUDIES_ERROR",

    SetTreatmentMapType = "treatment/SET_TREATMENT_MAP_TYPE",
    SetTreatmentDataset = "treatment/SET_TREATMENT_DATASET",
    SetPlasmodiumSpecies = "treatment/SET_TREATMENT_PLASMODIUM_SPECIES",
    SetDrug = "treatment/SET_TREATMENT_DRUG",
    SetMolecularMarker = "treatment/SET_MOLECULAR_MARKER",
    SetTreatmentFilteredStudies = "treatment/SET_FILTER_STUDIES",
    SetTreatmentSelectionStudies = "treatment/SET_SELECTION_STUDIES",
    SetExcludeLowerPatients = "treatment/SET_EXCLUDE_LOWER_PATIENTS",
    SetExcludeLowerSamples = "treatment/SET_EXCLUDE_LOWER_SAMPLES",

    FetchInvasiveStudiesRequest = "invasive/FETCH_INVASIVE_STUDIES_REQUEST",
    FetchInvasiveStudiesSuccess = "invasive/FETCH_INVASIVE_STUDIES_SUCCESS",
    FetchInvasiveStudiesError = "invasive/FETCH_INVASIVE_STUDIES_ERROR",

    SetInvasiveMapType = "invasive/SET_INVASIVE_MAP_TYPE",
    SetInvasiveDataset = "invasive/SET_INVASIVE_DATASET",
    SetInvasiveVectorSpecies = "invasive/SET_INVASIVE_VECTOR_SPECIES",
    SetInvasiveFilteredStudies = "invasive/SET_FILTER_STUDIES",
    SetInvasiveSelectionStudies = "invasive/SET_SELECTION_STUDIES",

    FetchTranslationsRequest = "translations/FETCH_TRANSLATIONS_REQUEST",
    FetchTranslationsSuccess = "translations/FETCH_TRANSLATIONS_SUCCESS",
    FetchTranslationsError = "translations/FETCH_TRANSLATIONS_ERROR",

    FetchCountryLayerRequest = "layers/FETCH_COUNTRY_LAYER_REQUEST",
    FetchCountryLayerSuccess = "layers/FETCH_COUNTRY_LAYER_SUCCESS",
    FetchCountryLayerError = "layers/FETCH_COUNTRY_LAYER_ERROR",

    AddNotification = "notifications/ADD_NOTIFICATION",
    DismissNotification = "notifications/DISMISS_NOTIFICATION",

    FetchDistrictsRequest = "layers/FETCH_DISTRICTS_REQUEST",
    FetchDistrictsSuccess = "layers/FETCH_DISTRICTS_SUCCESS",
    FetchDistrictsError = "layers/FETCH_DISTRICTS_ERROR",

    FetchDownloadsRequest = "downloads/FETCH_DOWNLOADS_REQUEST",
    FetchDownloadsSuccess = "downloads/FETCH_DOWNLOADS_SUCCESS",
    FetchDownloadsError = "downloads/FETCH_DOWNLOADS_ERROR",

    AddDownloadRequest = "downloads/ADD_DOWNLOAD_REQUEST",

    UploadFileRequest = "uploadFile/REQUEST",
    UploadFileSuccess = "uploadFile/SUCCESS",
    UploadFileError = "uploadFile/ERROR",

    FeedbackSetFields = "feedback/SET_FIELDS",
    FeedbackFieldChange = "feedback/SET_FIELD_CHANGE",
    FeedbackSetFieldErros = "feedback/SET_FIELD_ERRORS",
    FeedbackSubmit = "feedback/SUBMIT",
    FeedbackSuccess = "feedback/SUCCESS",
    FeedbackError = "feedback/ERROR",
}
