export enum THERAPEUTIC_EFFICACY_STUDIES_STATUS {
    ONGOING = "ONGOING",
    PLANNED = "PLANNED",
    COMPLETED = "COMPLETED",
    UNKNOWN = "UNKNOWN",
}

export const getTherapeuticEfficacyStudiesStatusFromStatusId = (statusId: number) => {
    const statusOptions: Record<string, number> = {
        [THERAPEUTIC_EFFICACY_STUDIES_STATUS.PLANNED]: 1,
        [THERAPEUTIC_EFFICACY_STUDIES_STATUS.ONGOING]: 2,
        [THERAPEUTIC_EFFICACY_STUDIES_STATUS.COMPLETED]: 3,
    };

    if (statusOptions[THERAPEUTIC_EFFICACY_STUDIES_STATUS.PLANNED] === statusId) {
        return THERAPEUTIC_EFFICACY_STUDIES_STATUS.PLANNED;
    }

    if (statusOptions[THERAPEUTIC_EFFICACY_STUDIES_STATUS.ONGOING] === statusId) {
        return THERAPEUTIC_EFFICACY_STUDIES_STATUS.ONGOING;
    }

    if (statusOptions[THERAPEUTIC_EFFICACY_STUDIES_STATUS.COMPLETED] === statusId) {
        return THERAPEUTIC_EFFICACY_STUDIES_STATUS.COMPLETED;
    }

    return THERAPEUTIC_EFFICACY_STUDIES_STATUS.UNKNOWN;
};
