export enum INTENSITY_STATUS {
    HIGH_INTENSITY = "HIGH_INTENSITY",
    MODERATE_TO_HIGH_INTENSITY = "MODERATE_TO_HIGH_INTENSITY",
    MODERATE_INTENSITY = "MODERATE_INTENSITY",
    LOW_INTENSITY = "LOW_INTENSITY",
    SUSCEPTIBLE = "SUSCEPTIBLE",
    UNKNOWN = "UNKNOWN",
}
