export interface TableData {
    ID: string;
    ISO2: string;
    COUNTRY: string;
    COUNTRY_NUMBER: number;
    SPECIES: string;
    INSECTICIDE_CLASSES: string;
    PYRETHROIDS_AVERAGE_MORTALITY: string;
    PYRETHROIDS_LAST_YEAR: string;
    ORGANOCHLORINES_AVERAGE_MORTALITY: string;
    ORGANOCHLORINES_LAST_YEAR: string;
    CARBAMATES_AVERAGE_MORTALITY: string;
    CARBAMATES_LAST_YEAR: string;
    ORGANOPHOSPHATES_AVERAGE_MORTALITY: string;
    ORGANOPHOSPHATES_LAST_YEAR: string;
    MONOXYGENASES_PERCENT_SITES_DETECTED: string;
    ESTERASES_PERCENT_SITES_DETECTED: string;
    GSTS_PERCENT_SITES_DETECTED: string;
    K1014S_PERCENT_SITES_DETECTED: string;
    K1014F_PERCENT_SITES_DETECTED: string;
    KDR_UNSPECIFIED_PERCENT_SITES_DETECTED: string;
    ACE1R_PERCENT_SITES_DETECTED: string;
}
