export interface CountryContextData {
    MAL_CALC_PERPF: number;
    MAL_CALC_PERPV: number;
    MAL_CALC_POP_AT_RISK_HIGH: number;
    MAL_CALC_POP_AT_RISK_LOW_HIGH: number;
    MAL_EST_MALARIA_CASES: number;
    MAL_EST_MALARIA_CASES_LOWER: number;
    MAL_EST_MALARIA_CASES_UPPER: number;
    MAL_EST_MALARIA_DEATHS: number;
    MAL_EST_MALARIA_DEATHS_LOWER: number;
    MAL_EST_MALARIA_DEATHS_UPPER: number;
    MAL_MAIN_MALARIA_VECTORS_VECTOR_1: string;
    MAL_MAIN_MALARIA_VECTORS_VECTOR_2: string;
    MAL_MAIN_MALARIA_VECTORS_VECTOR_3: string;
    MAL_MAIN_MALARIA_VECTORS_VECTOR_4: string;
    MAL_MAIN_MALARIA_VECTORS_VECTOR_5: string;
    MAL_MAIN_MALARIA_VECTORS_VECTOR_6: string;
    MAL_POP_UN: number;
    MAL_PROFILE_MEDICINE_FOR_1ST_LINE_TRT_OF_PF: string;
    MAL_PROFILE_MEDICINE_FOR_TRT_OF_PVIVAX: string;
    ORGANISATIONUNITCODE: string;
    ORGANISATIONUNIT_ISO2: string;
    ORGANISATIONUNITNAME: string;
    PERIODID: number;
}
